name: Extra TS Types

on:
  release:
    types: [created]

jobs:
  publish:
    if: startsWith(github.ref_name, 'extra-ts-types-v')
    runs-on: ubuntu-latest

    env:
      TAG_NAME: ${{github.ref_name}}
      PACKAGE_VERSION: ${TAG_NAME#extra-ts-types-v}

    steps:
      # - name: Set package version
      #   run: echo "" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm nx run extra-ts-types:publish
