name: Extra TS Types

on:
  release:
    types: [created]

jobs:
  publish:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/extra-ts-types-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
