name: Messenger / Publish

on:
  push:
    tags:
      - 'messenger-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Set package version
        run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#messenger-v}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test with Coverage
        run: pnpm nx run messenger:test/coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/libs/messenger/merged
          flags: messenger
          name: messenger-coverage
          fail_ci_if_error: false
          verbose: true

      - name: Publish
        run: pnpm nx run messenger:publish
